
# Copyright (C) 2024 OpenWrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Internet Access Schedule Control
LUCI_DESCRIPTION:=Web interface for controlling internet access schedules by MAC address and time
LUCI_DEPENDS:=
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-accesscontrol
PKG_VERSION:=2.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
